### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Gonzih** [bfabry/zeppelin-clojure-interpreter#1]
Hi man, I got interested in clojure integration in the apache zeppelin, found your project. But there is no documentation at all. How do I build it? How do I install it? Any chance that you can improve on that?

Thanks a lot! Cheers!

**Comment by xafero** [comment]
Hi Gonzih, did you see https://github.com/oubiwann/zeppelin-clojure-interpreter ? It is old, too, but maybe a start

**Comment by bzz** [comment]
There is also a https://github.com/whamtet/zeppelin-clojure-interpreter
